name: 'Changeset Check for PR'
'on':
    pull_request: null
env:
    key: cache-v0.1

jobs:
    yarn_install:
        strategy:
            fail-fast: false
            matrix:
                operating-system:
                    - ubuntu-latest
        runs-on: '${{ matrix.operating-system }}'
        name: 'Building The App / ${{ matrix.operating-system }}'

        steps:
            -
              name: Checkout
              uses: actions/checkout@v3

            - 
              name: Add target branch in repo 
              run: |
                    git fetch --no-tags --depth=1 origin $GITHUB_BASE_REF
                    git checkout -b $GITHUB_BASE_REF
                    git checkout -

            - 
                name: Yarn install
                run: yarn install --immutable


            -
                name: Changeset status
                run: npx changeset status --since=$GITHUB_BASE_REF
