name: 'CI Monorepo '
'on':
    push:
        branches:
            - main
    pull_request: null
env:
    key: cache-v0.1

jobs:
    yarn_install:
        strategy:
            fail-fast: false
            matrix:
                operating-system:
                    - ubuntu-latest
        runs-on: '${{ matrix.operating-system }}'
        name: 'Building The App / ${{ matrix.operating-system }}'

        steps:
            - uses: actions/checkout@v3
            - run: |
                    git fetch --no-tags --depth=1 origin master
                    git checkout -b main
                    git checkout ${{ github.event.pull_request.head.sha }}

            -
                name: Cache node_modules
                uses: actions/cache@v3
                id: yarn-cache-node-modules
                with:
                    path: node_modules
                    key: ${{ runner.os }}-yarn-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-yarn-cache-node-modules-

            - 
                name: Yarn install
                run: yarn install --immutable


            -
                name: Changeset status
                run: git branch -vvv && npx changeset status 
