name: 'CI Monorepo '
'on':
    push:
        branches:
            - main
    pull_request: null
env:
    key: cache-v0.1

jobs:
    yarn_install:
        strategy:
            fail-fast: false
            matrix:
                operating-system:
                    - ubuntu-latest
        runs-on: '${{ matrix.operating-system }}'
        name: 'Building The App / ${{ matrix.operating-system }}'

        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            - 
                name: Yarn install
                run: yarn install --immutable


            -
                name: Changeset status
                run: npx changeset status 
